apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-node-script-runner
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-node-script-runner-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  k8s-node-script-runner-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  k8s-node-script-runner-role
subjects:
- kind: ServiceAccount
  name:  k8s-node-script-runner
  namespace: default