  apiVersion: apps/v1
  kind: DaemonSet 
  metadata:
    name: nodescriptrunner
    labels:
      app: nodescriptrunner
  spec:  
    selector:
      matchLabels:
        app: nodescriptrunner
    template:
      metadata:
        labels:
          app: nodescriptrunner
      spec:
        hostPID: true
        hostNetwork: true
        serviceAccountName: k8s-node-script-runner
        containers:
        - name: nodescriptrunner
          image: DockerhubName/nodescriptrunner:v1.0
          imagePullPolicy: Always          
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"